Repository BenoitAnastay/paperless-home-assistant-addon, pull requests merged in 2025-02, with the labels that each got.

#227 ⬆️ Update redis to 5:7.0.15-1~deb12u2
  paperless-ngx/Dockerfile
Labels: dependencies

#232 🚑️ Fix Zxing for ARM
  paperless-ngx/Dockerfile
Labels: bugfix

#233 update badges
  README.md
  paperless-ngx/.README.j2
Labels: documentation

#239 🔧 Update default filename format
  paperless-ngx/config.yaml
Labels: enhancement
